server:
  port: 5000

spring:
  application:
    name: file-upload-project

servlet:
  multipart:
    file-size-threshold: 0B
    max-file-size: 100MB
    max-request-size: 100MB

cloud:
  aws:
    credentials:
      access-key: ${ACCESSKEY}
      secret-key: ${SECRETKEY}
    region:
      static: ${REGION}